### ISSUE TITLE
测试了下新版本0.2

### ISSUE THREAD

**Issue by lki2019** [ingbyr/VDM#12]
![qq 20170927095235](https://user-images.githubusercontent.com/30022431/30892270-3be4afb6-a36a-11e7-940e-b8b5390e3fd0.png)

下载完成后 还是有这个框，要手动关闭。

希望下一版本可以增加批量添加网址，批量下载就好了，

设置选项里可以选择最高清晰度，点上沟即代表下载所有视频都下载最高画质的

这样就不用再选择了，省去了一步，

还有可以把这个https://github.com/zhangn1985/ykdl/releases/

项目 也添加进去，ykdl 侧重的是国内网址下载，很多时候还是可以的

这样youtube-dl  you-get ykdl  3个一起支持就好了

不着急 慢慢来，感谢作者的好项目····

**Comment by lki2019** [comment]
![qq 20170927101939](https://user-images.githubusercontent.com/30022431/30892932-ec495994-a36d-11e7-82d1-8dcf86891955.png)

这个暂停好像有点问题，

点暂停后，的确暂停了，我在点一下，他不继续下载啊，

是不是这里有点问题，点暂停后，pause 变成继续  
点继续后 继续下载，然后又变成pause

**Comment by lki2019** [comment]
![qq 20170927102512](https://user-images.githubusercontent.com/30022431/30893072-aac9c016-a36e-11e7-9df9-a443f83b94d0.png)

又测试了下，的确下载完成后，那个框还在，速度还在，pause还在，

下载完成后，显示下载已完成  这样比较好吧，

**Comment by ingbyr** [comment]
交互逻辑还是需要改进的，感谢建议！

**Comment by msongz** [comment]
很好用！ 首页路径旁边加一个 open path 吧~

**Comment by freesky0926** [comment]
大神，这个到底怎么用啊，下载完文件不知道软件在哪？

**Comment by megaslx** [comment]
可以考虑在下载完毕之后把pause按钮变成finish按钮，点打叉没有点大按钮来的方便
另外就是proxy的设置能否可以在勾掉之后继续保存？经常会下youtube和youku的视频，每次下了youku的之后proxy就要重新填写。
