### ISSUE TITLE
无法正常打开VDM

### ISSUE THREAD

**Issue by nanba-dengtao** [ingbyr/VDM#61]
点击后桌面图标后无法运行，也没有错误提示，在0.23版本可以正常运行，电脑是win10家庭版

**Comment by ingbyr** [comment]
在C:\Users\用户名\ 下有.vdm文件夹吗

**Comment by BigNeo** [comment]
你好，问题如@nanba ，双击桌面图标之后 程序无反应，以前gui-youget版本的时候 一直是可以使用的，系统是win10 周年版，x64. c盘没有vdm文件夹。 我是吧vdm安装到其他盘了。

**Comment by nanba-dengtao** [comment]
@BigNeo 你好，我的问题已解决，你看下安装目录是否为全英文，如果不是换个全英文的目录安装

**Comment by BigNeo** [comment]
你好，问题已经解决，好像无关英文，我只是安装在c盘下面，而不是其他盘就没事了。 两个盘都是全英文。
Dr.Daniel
