### ISSUE TITLE
VDM是只能win10系统吗？以后有可能支持win7吗？

### ISSUE THREAD

**Issue by rashohan** [ingbyr/VDM#72]
win7 32位，安装完打不开。显示“此文件的版本与正在运行的windows版本不兼容”。

**Comment by hunsui** [comment]
不是不支持win7而是不支持32位

**Comment by rashohan** [comment]
win7用户32位的也很多，为何只支持win764位呢？请求加入支持32位可以吗？？

**Comment by ingbyr** [comment]
目前可以自行安装 [JRE8](http://www.oracle.com/technetwork/java/javase/downloads/jre8-downloads-2133155.html)，然后使用.jar格式运行
