### ISSUE TITLE
youtube链接获取资源失败，我是用的shadowsocks翻墙，怎么设置呢

### ISSUE THREAD

**Issue by zhaoliang0302** [ingbyr/VDM#77]
Please make sure these boxes are checked before submitting your issue – thank you!

- [ ] You can actually watch the video in your browser, but not download them with `VDM`.
- [ ] Your `VDM` is up-to-date.
- [ ] Your downloading engine is up-to-date.

Please paste the full `%HOMEPATH%\.vdm\log\debug.log` inside the fences:

```
[PASTE IN ME]
```

If there's anything else you would like to say(e.g some new features) fill in the box below
> [WRITE SOMETHING]

在提交前，请确保您已经检查了以下内容!

- [ ] 你可以在浏览器中观看视频，但不能使用`VDM`下载。
- [ ] 您的`VDM`为最新版。
- [ ] 您的下载引擎为最新版。
 
请将`%HOMEPATH%\.vdm\log\debug.log`文件内容粘贴在下面：

```
[在这里粘贴完整日志]
```

如果您有其他留言（如需要新特性等），请在下面添加：
> [您的留言]

**Comment by hongweifon** [comment]
邮件咋取消啊？不要转给我了谢谢

**Comment by zhaoliang0302** [comment]
不是我转发给你。。。。是github回复内容会邮件推送给你，你可以搜一下怎么取消



zhaoliang0302@gmail.com
 
发件人： hongweifon
发送时间： 2019-03-29 14:48
收件人： ingbyr/VDM
抄送： Liang Zhao; State change
主题： Re: [ingbyr/VDM] youtube链接获取资源失败，我是用的shadowsocks翻墙，怎么设置呢 (#77)
邮件咋取消啊？不要转给我了谢谢

**Comment by Warm-rain** [comment]
two have a good sense of humor! hahah
